/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JaLAJniLite_jni_blas_jniCBLAS */

#ifndef _Included_JaLAJniLite_jni_blas_jniCBLAS
#define _Included_JaLAJniLite_jni_blas_jniCBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dscal
 * Signature: (ID[DI)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dscal
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray, jint);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    daxpy
 * Signature: (ID[DI[DI)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_daxpy
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    ddot
 * Signature: (I[DI[DI)D
 */
JNIEXPORT jdouble JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_ddot
  (JNIEnv *, jclass, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dgemv
 * Signature: (IIIID[D[DID[DI)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dgemv
  (JNIEnv *, jclass, jint, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jint, jdouble, jdoubleArray, jint);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dtrmv
 * Signature: (IIIII[D[DI)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dtrmv
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dsymv
 * Signature: (IIID[D[DID[DI)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dsymv
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jint, jdouble, jdoubleArray, jint);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dgemm
 * Signature: (IIIIIID[D[DD[D)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dgemm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dtrmm
 * Signature: (IIIIIIID[D[D)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dtrmm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     JaLAJniLite_jni_blas_jniCBLAS
 * Method:    dsymm
 * Signature: (IIIIID[D[DD[D)V
 */
JNIEXPORT void JNICALL Java_JaLAJniLite_jni_1blas_jniCBLAS_dsymm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class JaLAJniLite_jni_blas_jniCBLAS_SIDE */

#ifndef _Included_JaLAJniLite_jni_blas_jniCBLAS_SIDE
#define _Included_JaLAJniLite_jni_blas_jniCBLAS_SIDE
#ifdef __cplusplus
extern "C" {
#endif
#undef JaLAJniLite_jni_blas_jniCBLAS_SIDE_Left
#define JaLAJniLite_jni_blas_jniCBLAS_SIDE_Left 141L
#undef JaLAJniLite_jni_blas_jniCBLAS_SIDE_Right
#define JaLAJniLite_jni_blas_jniCBLAS_SIDE_Right 142L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class JaLAJniLite_jni_blas_jniCBLAS_DIAG */

#ifndef _Included_JaLAJniLite_jni_blas_jniCBLAS_DIAG
#define _Included_JaLAJniLite_jni_blas_jniCBLAS_DIAG
#ifdef __cplusplus
extern "C" {
#endif
#undef JaLAJniLite_jni_blas_jniCBLAS_DIAG_NonUnit
#define JaLAJniLite_jni_blas_jniCBLAS_DIAG_NonUnit 131L
#undef JaLAJniLite_jni_blas_jniCBLAS_DIAG_Unit
#define JaLAJniLite_jni_blas_jniCBLAS_DIAG_Unit 132L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class JaLAJniLite_jni_blas_jniCBLAS_UPLO */

#ifndef _Included_JaLAJniLite_jni_blas_jniCBLAS_UPLO
#define _Included_JaLAJniLite_jni_blas_jniCBLAS_UPLO
#ifdef __cplusplus
extern "C" {
#endif
#undef JaLAJniLite_jni_blas_jniCBLAS_UPLO_Upper
#define JaLAJniLite_jni_blas_jniCBLAS_UPLO_Upper 121L
#undef JaLAJniLite_jni_blas_jniCBLAS_UPLO_Lower
#define JaLAJniLite_jni_blas_jniCBLAS_UPLO_Lower 122L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE */

#ifndef _Included_JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE
#define _Included_JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE
#ifdef __cplusplus
extern "C" {
#endif
#undef JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE_NoTrans
#define JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE_NoTrans 111L
#undef JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE_Trans
#define JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE_Trans 112L
#undef JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE_ConjTrans
#define JaLAJniLite_jni_blas_jniCBLAS_TRANSPOSE_ConjTrans 113L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class JaLAJniLite_jni_blas_jniCBLAS_LAYOUT */

#ifndef _Included_JaLAJniLite_jni_blas_jniCBLAS_LAYOUT
#define _Included_JaLAJniLite_jni_blas_jniCBLAS_LAYOUT
#ifdef __cplusplus
extern "C" {
#endif
#undef JaLAJniLite_jni_blas_jniCBLAS_LAYOUT_RowMajor
#define JaLAJniLite_jni_blas_jniCBLAS_LAYOUT_RowMajor 101L
#undef JaLAJniLite_jni_blas_jniCBLAS_LAYOUT_ColMajor
#define JaLAJniLite_jni_blas_jniCBLAS_LAYOUT_ColMajor 102L
#ifdef __cplusplus
}
#endif
#endif
